### ISSUE TITLE
Checklist for v2.0.0

### ISSUE THREAD

**Issue by msberends** [msberends/AMR#63]
Incorporate these changes for v2.0.0, expected to hit CRAN in January/February 2023:

- [x] Implement new algorithm for microorganisms determination
  - [x] e.g. #54 
  - [x] Read about `stringdist` package, maybe include some code to this package (license is compatible, be sure to add attribution)
- [x] Translations:
  - [x] Add more translations (check with Deepl), such as Ukrainian, Turkish, Greek, Japanese, Polish, simplified Chinese
  - [x] #64
  - [x] Add instruction to repo documentation
  - [x] Add new `data-raw/_language_update.R` workflow
- [x] Update `antibiotics` data set
  - [x] #62 
  - [x] Update `antibiotics` data set with new DDDs, etc.
  - [x] Check WHOCC website for missing antibiotic agents - all of J0 should be present in our data set
- [x] Include latest EUCAST and CLSI breakpoints (check with WHONET), and EUCAST Expert Rules (probably 2023 guidelines), also add v12 of expert rules and update `intrinsic_resistant`
- [x] Update the `microorganisms` data set
  - [x] Change all references from CoL to GBIF, also on website and internal variables
  - [x] Update reproduction script to rely on [DOI 10.15468/39omei](https://doi.org/10.15468/39omei) and latest LPSN
  - [x] Be sure to cite right: *GBIF Secretariat (2021). GBIF Backbone Taxonomy. Checklist dataset https://doi.org/10.15468/39omei accessed via GBIF.org on 2022-09-02* (parametrise date with R Markdown)
  - [x] Include new identifiers: `species_id` should contain TaxonID from GBIF records, otherwise LPSN record number
  - [x] Include #51 
  - [x] Remove families without genera, order without families, classes without orders, phyla without classes
  - [x] ~~Develop new microbial codes that are more reproducible and sustainable, yet still readable + add translation from older versions~~ Won’t do - codes would become too lengthy 
- [x] Try to increase speed of `first_isolate()`, `get_new_episode()`
- [x] Get rid of `git_development.sh` and `git_merge.sh` workflows (replace with git pre-commit hook)
- [x] Update website
  - [x] `pkgdown` 2.0.0 and Bootstrap 5
  - [x] #56 after each push to `main` branch using GHA
  - [x] Be sure to read https://pkgdown.r-lib.org/articles/customise.html#bslib-variables for setting font and colours, instead of separate CSS file
- [x] #57 
- [x] #59
- [x] #60 
- [x] Write developers guideline to explain how things work in this repo
- [x] Update `CITATION` to include our JSS paper, also put DOI in the description of the `DESCRIPTION` file + edit Welcome vignette and website index accordingly
- [x] Convert all data sets to tibbles, also update unit tests
- [x] Rewrite GitHub Actions flows
- [x] #69
- [x] #77, to fix #76
- [x] Move `type_sum()` to pillar
- [x] #66 
- [x] #93
